- name: Terminal config
  tags:
    - terminal
  block:
    - name: Ensure ghostty dir exists
      file:
        path: ~/.config/ghostty
        state: directory

    - name: Stow ghostty config
      shell: >
        stow --adopt -t ~/.config/ghostty/ -d dotfiles ghostty
      
    - name: Change default shell to fish
      when: ansible_os_family == "Darwin"
      become: yes
      shell: >
        chsh -s /usr/local/bin/fish

    - name: Change default shell to fish
      become: yes
      shell: >
        chsh -s /usr/bin/fish


    - name: Install fisher plugin manager for fish
      become: false
      ansible.builtin.shell: |
        fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'
      args:
        executable: /bin/bash
      environment:
        HOME: "{{ ansible_env.HOME }}"
      when: ansible_env.SHELL is search('fish')

    - name: Ensure fish dir exists
      file:
        path: ~/.config/fish
        state: directory

    - name: Stow fish config
      shell: >
        stow --adopt -t ~/.config/fish/ -d dotfiles fish

    - name: Stow starship config
      shell: >
        stow --adopt -t ~/.config/ -d dotfiles starship

    - name: Install zoxide with Homebrew
      when: ansible_os_family == "Darwin"
      homebrew:
        name: zoxide
        state: present

